### ISSUE TITLE
Sort events by date

### ISSUE THREAD

**Issue by fpietrosanti** [ConfWatch/confwatchd#6]
This ticket is to sort the events submitted by the date when they will happens.

**Comment by evilsocket** [comment]
Send PRs, not tickets.

**Comment by fpietrosanti** [comment]
Tickets enable contributors with coding capacity and willness to send PR

**Comment by evilsocket** [comment]
Contributors with coding capacity and willness to send PR are already smart enough to figure out themselves there's no sorting by date on the website, since this is not functionally a necessity (events are already sorted from oldest to newest in most views), I'd rather not have an issue open.

**Comment by fpietrosanti** [comment]
perfectionist :*

**Comment by evilsocket** [comment]
Always! :D (actually it's just thc messing with short term memory, if I leave this open after a few days will not remember if this is needed or not XD)
